name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Install pubversion
        run: dart pub global activate pubversion

      - name: Increment version
        run: dart pub global run pubversion patch

      - name: Commit version changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pubspec.yaml
          git commit -m "Increment version [skip ci]" || echo "No changes to commit"
          git push

      - name: Build Web
        run: flutter build web --release --base-href /minesweeper/

      - name: Verify build output
        run: ls -R build/web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # This publishes the content of the ./build/web directory to the gh-pages branch
          publish_dir: ./build/web
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
